FROM python:3.10-slim

ENV DEBIAN_FRONTEND=noninteractive \
    MPLBACKEND=Agg \
    MPLCONFIGDIR=/cache \
    XDG_CACHE_HOME=/cache

RUN apt-get update && apt-get install -y --no-install-recommends \
    git wget curl build-essential \
 && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip 

RUN pip install git+https://github.com/sokrypton/ColabFold.git@main
RUN pip install --no-cache-dir alphafold-colabfold

# ENTRYPOINT ["colabfold_batch"]
